version: '3'
services:
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb-data:/data/db
    networks:
      - book-rental-app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=docker
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DB=book-rental-app-db
    depends_on:
      - mongodb
    networks:
      - book-rental-app-network

networks:
  book-rental-app-network:

volumes:
  mongodb-data:
